# disabled_rules: # rule identifiers to exclude from running
#   - trailing_whitespace
# opt_in_rules: # some rules are only opt-in
#   - force_unwrapping
  # Find all the available rules by running:
  # swiftlint rules
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - fastlane

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 160
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  # - 400 # error
# or they can set both explicitly
file_length:
  warning: 900
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 50
    error: 60
  excluded: iPhone # excluded via string
identifier_name:
  min_length: 2 # only min_length
  excluded: # excluded via string array
    - i # as for index
    - j # as for index
large_tuple: 3
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
